
CREATE TABLE characters (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    confession VARCHAR(50),
    first_date VARCHAR(50),
    most_loved VARCHAR(50),
    turn_off VARCHAR(50),
    physique VARCHAR(50),
    crime VARCHAR(50)
);

INSERT INTO characters (name, confession, first_date, most_loved, turn_off, physique, crime) VALUES
('Frieren', 'You', 'Park', 'Getting headpats', 'Possessive', 'Easy win', 'Something stupid'),
('Fern', 'You', 'Cafe', 'Sharing an ice-cream cone', 'Optimistic', 'Lose on purpose', 'Falsely accused'),
('Stark', 'Them', 'Arcade', 'Raiding a castle', 'Pessimistic', 'Complete loss', 'Falsely accused'),
('Himmel', 'Them', 'Cinema', 'Sharing an ice-cream cone', 'Pessimistic', 'Tactical', 'Something stupid'),
('Übel', 'Them', 'I don’t care', 'Raiding a castle', 'Optimistic', 'Complete loss', 'Murder'),
('Elric Edward', 'Them', 'Cafe', 'Raiding a castle', 'Pessimistic', 'Close match', 'Something stupid'),
('Elric Alphonse', 'Them', 'I don’t care', 'Raiding a castle', 'Possessive', 'Complete loss', 'Falsely accused'),
('Mustang Roy', 'Them', 'Cinema', 'Sharing an ice-cream cone', 'Possessive', 'Tactical', 'Arrested for a good cause'),
('Hughes Maes', 'Them', 'Park', 'Getting headpats', 'Pessimistic', 'Tactical', 'Arrested for a good cause'),
('Hawkeye Riza', 'You', 'Cafe', 'Sharing an ice-cream cone', 'Optimistic', 'Complete loss', 'Arrested for a good cause'),
('Rockbell Winry', 'You', 'Park', 'Raiding a castle', 'Pessimistic', 'Close match', 'Falsely accused'),
('Okabe Rintarou', 'You', 'Arcade', 'Raiding a castle', 'Pessimistic', 'Easy win', 'Something stupid'),
('Makise Kurisu', 'You', 'Cafe', 'Sharing an ice-cream cone', 'Optimistic', 'Lose on purpose', 'Falsely accused'),
('Shiina Mayuri', 'Them', 'Park', 'Getting headpats', 'Pessimistic', 'Lose on purpose', 'Falsely accused'),
('Hashida Itaru', 'Them', 'Cafe', 'Raiding a castle', 'Pessimistic', 'Close match', 'Something stupid'),
('Amane Suzuha', 'Them', 'Park', 'Defends you with their life', 'Pretentious', 'Close win', 'Arrested for a good cause'),
('Urushibara Ruka', 'You', 'Cafe', 'Sharing an ice-cream cone', 'Optimistic', 'Tactical', 'Falsely accused'),
('Kiryuu Moeka', 'You', 'Cinema', 'Getting headpats', 'Optimistic', 'Tactical', 'Murder'),
('Yeager Eren', 'You', 'Park', 'Getting headpats', 'Pretentious', 'Close win', 'Falsely accused'),
('Ackerman Mikasa', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Optimistic', 'Tactical', 'Something stupid'),
('Levi Rivaille', 'You', 'Arcade', 'Raiding a castle', 'Pretentious', 'Close win', 'Falsely accused'),
('Arlert Armin', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Possessive', 'Tactical', 'Something stupid'),
('Jaeger Grisha', 'You', 'Park', 'Getting headpats', 'Optimistic', 'Complete loss', 'Falsely accused'),
('Smith Erwin', 'Them', 'Cinema', 'Raiding a castle', 'Pessimistic', 'Easy win', 'Murder'),
('Zoë Hange', 'You', 'Park', 'Sharing an ice-cream cone', 'Possessive', 'Close win', 'Falsely accused'),
('Blouse Sasha', 'Them', 'Cafe', 'Getting headpats', 'Optimistic', 'Tactical', 'Something stupid'),
('Braun Reiner', 'You', 'Arcade', 'Sharing an ice-cream cone', 'Pessimistic', 'Complete loss', 'Falsely accused'),
('Kirstein Jean', 'Them', 'Cinema', 'Raiding a castle', 'Possessive', 'Easy win', 'Murder'),
('Ackerman Kenny', 'You', 'Park', 'Getting headpats', 'Optimistic', 'Tactical', 'Something stupid'),
('Reiss Historia', 'Them', 'Cafe', 'Raiding a castle', 'Pessimistic', 'Complete loss', 'Falsely accused'),
('Leonhart Annie', 'You', 'Park', 'Getting headpats', 'Optimistic', 'Tactical', 'Something stupid'),
('Shinomiya Kaguya', 'You', 'I don’t care', 'Getting headpats', 'Optimistic', 'Complete loss', 'Falsely accused'),
('Ishigami Yuu', 'You', 'Arcade', 'Raiding a castle', 'Pretentious', 'Close match', 'Arrested for a good cause'),
('Fujiwara Chika', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Pessimistic', 'Tactical', 'Something stupid'),
('Shirogane Miyuki', 'You', 'Park', 'Getting headpats', 'Optimistic', 'Tactical', 'Arrested for a good cause'),
('Iino Miko', 'You', 'Cafe', 'Sharing an ice-cream cone', 'Optimistic', 'Easy win', 'Falsely accused'),
('Hayasaka Ai', 'Them', 'I don’t care', 'Raiding a castle', 'Pretentious', 'Complete loss', 'Arrested for a good cause'),
('Okazaki Tomoya', 'You', 'I don’t care', 'Sharing an ice-cream cone', 'Optimistic', 'Tactical', 'Falsely accused'),
('Furukawa Nagisa', 'You', 'Park', 'Getting headpats', 'Pessimistic', 'Complete loss', 'Falsely accused'),
('Okazaki Ushio', 'Them', 'Park', 'Sharing an ice-cream cone', 'Pessimistic', 'Lose on purpose', 'Something stupid'),
('Sakagami Tomoyo', 'You', 'Park', 'Defends you with their life', 'Possessive', 'Complete loss', 'Falsely accused'),
('Fujibayashi Kyou', 'You', 'Arcade', 'Getting headpats', 'Pessimistic', 'Complete loss', 'Arrested for a good cause'),
('Fujibayashi Ryou', 'Them', 'Arcade', 'Getting headpats', 'Pretentious', 'Easy win', 'Arrested for a good cause'),
('Gojo Satoru', 'Them', 'Arcade', 'Raiding a castle', 'Pessimistic', 'Complete loss', 'Something stupid'),
('Itadori Yuuji', 'Them', 'Arcade', 'Raiding a castle', 'Pretentious', 'Complete loss', 'Something stupid'),
('Fushiguro Megumi', 'You', 'I don’t care', 'Defends you with their life', 'Optimistic', 'Close match', 'Arrested for a good cause'),
('Kugisaki Nobara', 'Them', 'Arcade', 'Raiding a castle', 'Pessimistic', 'Complete loss', 'Something stupid'),
('Nanami Kento', 'You', 'Park', 'Defends you with their life', 'Optimistic', 'Complete loss', 'Arrested for a good cause'),
('Ryomen Sukuna', 'Them', 'Arcade', 'Raiding a castle', 'Pessimistic', 'Complete loss', 'Murder'),
('Okkotsu Yuuta', 'Them', 'Park', 'Getting headpats', 'Pretentious', 'Tactical', 'Arrested for a good cause'),
('Fushiguro Toji', 'Them', 'Arcade', 'Raiding a castle', 'Pessimistic', 'Complete loss', 'Murder'),
('Zenin Maki', 'Them', 'I don’t care', 'Defends you with their life', 'Pretentious', 'Complete loss', 'Falsely accused'),
('Inumaki Toge', 'You', 'Cafe', 'Sharing an ice-cream cone', 'Possessive', 'Complete loss', 'Arrested for a good cause'),
('Panda', 'You', 'Park', 'Getting headpats', 'Optimistic', 'Close match', 'Something stupid'),
('Fushiguro Toji', 'Them', 'Arcade', 'Raiding a castle', 'Pessimistic', 'Complete loss', 'Murder'),
('Zenin Maki', 'Them', 'I don’t care', 'Defends you with their life', 'Pretentious', 'Complete loss', 'Falsely accused'),
('Inumaki Toge', 'You', 'Cafe', 'Sharing an ice-cream cone', 'Pessimistic', 'Complete loss', 'Something stupid'),
('Senjougahara Hitagi', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Optimistic', 'Tactical', 'Murder'),
('Araragi Koyomi', 'You', 'Park', 'Getting headpats', 'Optimistic', 'Tactical', 'Something stupid'),
('Hanekawa Tsubasa', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Pessimistic', 'Complete loss', 'Something stupid'),
('Oshino Shinobu', 'You', 'Park', 'Sharing an ice-cream cone', 'Pessimistic', 'Close win', 'Something stupid'),
('Oshino Meme', 'Them', 'Arcade', 'Raiding a castle', 'Optimistic', 'Tactical', 'Something stupid'),
('Kanbaru Suruga', 'You', 'Park', 'Sharing an ice-cream cone', 'Pessimistic', 'Close win', 'Something stupid'),
('Hachikuji Mayoi', 'Them', 'Cafe', 'Getting headpats', 'Optimistic', 'Easy win', 'Something stupid'),
('Sengoku Nadeko', 'You', 'Park', 'Sharing an ice-cream cone', 'Possessive', 'Close win', 'Something stupid'),
('Nakano Ichika', 'Them', 'Cinema', 'Sharing an ice-cream cone', 'Possessive', 'Close match', 'Something stupid'),
('Nakano Nino', 'Them', 'Cinema', 'Sharing an ice-cream cone', 'Optimistic', 'Tactical', 'Falsely accused'),
('Nakano Miku', 'You', 'Arcade', 'Sharing an ice-cream cone', 'Optimistic', 'Lose on purpose', 'Falsely accused'),
('Nakano Yotsuba', 'Them', 'Arcade', 'Raiding a castle', 'Pessimistic', 'Close match', 'Something stupid'),
('Nakano Itsuki', 'You', 'I don’t care', 'Getting headpats', 'Possessive', 'Tactical', 'Falsely accused'),
('Makima', 'Them', 'I don’t care', 'Getting headpats', 'Possessive', 'Complete loss', 'Murder'),
('Denji', 'Them', 'Cafe', 'Raiding a castle', 'Pretentious', 'Complete loss', 'Something stupid'),
('Power', 'Them', 'Arcade', 'Raiding a castle', 'Possessive', 'Complete loss', 'Something stupid'),
('Himeno', 'Them', 'Cinema', 'Getting headpats', 'Possessive', 'Complete loss', 'Arrested for a good cause'),
('Mizuhara Chizuru', 'You', 'Cinema', 'Getting headpats', 'Pretentious', 'Close match', 'Falsely accused'),
('Kamado Tanjiro', 'Them', 'Cafe', 'Defends you with their life', 'Pretentious', 'Complete loss', 'Arrested for a good cause'),
('Nezuko Kamado', 'You', 'Cafe', 'Getting headpats', 'Pretentious', 'Complete loss', 'Something stupid'),
('Zenitsu Agatsuma', 'Them', 'I don’t care', 'Raiding a castle', 'Optimistic', 'Close match', 'Something stupid'),
('Inosuke Hashibira', 'Them', 'Arcade', 'Raiding a castle', 'Pessimistic', 'Complete loss', 'Something stupid'),
('Shinobu Kocho', 'Them', 'Park', 'Getting headpats', 'Optimistic', 'Complete loss', 'Falsely accused'),
('Giyu Tomioka', 'You', 'I don’t care', 'Defends you with their life', 'Optimistic', 'Complete loss', 'Arrested for a good cause'),
('Kyojuro Rengoku', 'Them', 'Cinema', 'Getting headpats', 'Pessimistic', 'Complete loss', 'Something stupid'),
('Tengen Uzui', 'Them', 'Cinema', 'Raiding a castle', 'Possessive', 'Complete loss', 'Arrested for a good cause'),
('Mitsuri Kanroji', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Pessimistic', 'Lose on purpose', 'Arrested for a good cause'),
('Muzan Kibutsuji', 'Them', 'Cinema', 'Getting headpats', 'Optimistic', 'Complete loss', 'Murder'),
('Midoriya Izuku', 'You', 'Arcade', 'Defends you with their life', 'Pretentious', 'Tactical', 'Arrested for a good cause'),
('Aisaka Taiga', 'You', 'Arcade', 'Raiding a castle', 'Optimistic', 'Complete loss', 'Something stupid'),
('Akame', 'You', 'I don’t care', 'Defends you with their life', 'Pretentious', 'Complete loss', 'Falsely accused'),
('Zero Two', 'Them', 'Cafe', 'Getting headpats', 'Pessimistic', 'Complete loss', 'Something stupid'),
('Rudeus Greyrat', 'You', 'Arcade', 'Raiding a castle', 'Possessive', 'Easy win', 'Murder'),
('Hoshino Aqua', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Pessimistic', 'Complete loss', 'Falsely accused'),
('Miyazono Kaori', 'Them', 'Cinema', 'Raiding a castle', 'Pessimistic', 'Easy win', 'Something stupid'),
('David Martinez', 'Them', 'Arcade', 'Raiding a castle', 'Pretentious', 'Close win', 'Something stupid'),
('Sakuta Azusagawa', 'Them', 'I don’t care', 'Defends you with their life', 'Pretentious', 'Tactical', 'Arrested for a good cause'),
('Hikigaya Hachiman', 'Them', 'I don’t care', 'Raiding a castle', 'Optimistic', 'Tactical', 'Arrested for a good cause'),
('Ciel Phantomhive', 'You', 'I don’t care', 'Raiding a castle', 'Optimistic', 'Easy win', 'Falsely accused'),
('Miyamura Izumi', 'Them', 'I don’t care', 'Raiding a castle', 'Pretentious', 'Complete loss', 'Falsely accused'),
('Tohru Honda', 'Them', 'Park', 'Getting headpats', 'Pretentious', 'Lose on purpose', 'Something stupid'),
('Kasumigaoka Utaha', 'Them', 'Cafe', 'Getting headpats', 'Optimistic', 'Close match', 'Murder'),
('Narumi Momose', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Pessimistic', 'Lose on purpose', 'Something stupid'),
('Kitagawa Marin', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Pretentious', 'Easy win', 'Something stupid'),
('Ayuzawa Misaki', 'You', 'I don’t care', 'Getting headpats', 'Pessimistic', 'Complete loss', 'Arrested for a good cause'),
('Onodera Kosaki', 'You', 'Cafe', 'Sharing an ice-cream cone', 'Pretentious', 'Lose on purpose', 'Something stupid');
