CREATE TABLE characters (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    confession VARCHAR(50),
    first_date VARCHAR(50),
    most_loved VARCHAR(50),
    turn_off VARCHAR(50),
    physique VARCHAR(50),
    crime VARCHAR(50),
    image VARCHAR(255)
);

INSERT INTO characters (name, confession, first_date, most_loved, turn_off, physique, crime, image) VALUES
('Frieren', 'You', 'Park', 'Getting headpats', 'Possessive', 'Easy win', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/7/525105.jpg'),
('Fern', 'You', 'Cafe', 'Sharing an ice-cream cone', 'Optimistic', 'Lose on purpose', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/13/519083.jpg'),
('Stark', 'Them', 'Arcade', 'Raiding a castle', 'Pessimistic', 'Complete loss', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/2/523292.jpg'),
('Himmel', 'Them', 'Cinema', 'Sharing an ice-cream cone', 'Pessimistic', 'Tactical', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/9/523295.jpg'),
('Übel', 'Them', 'I don''t care', 'Raiding a castle', 'Optimistic', 'Complete loss', 'Murder', 'https://cdn.myanimelist.net/images/characters/9/543072.jpg'),
('Elric Edward', 'Them', 'Cafe', 'Raiding a castle', 'Pessimistic', 'Close match', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/9/72533.jpg'),
('Elric Alphonse', 'Them', 'I don''t care', 'Raiding a castle', 'Possessive', 'Complete loss', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/5/54265.jpg'),
('Mustang Roy', 'Them', 'Cinema', 'Sharing an ice-cream cone', 'Possessive', 'Tactical', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/11/510227.jpg'),
('Hughes Maes', 'Them', 'Park', 'Getting headpats', 'Pessimistic', 'Tactical', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/13/73469.jpg'),
('Hawkeye Riza', 'You', 'Cafe', 'Sharing an ice-cream cone', 'Optimistic', 'Complete loss', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/3/451785.jpg'),
('Rockbell Winry', 'You', 'Park', 'Raiding a castle', 'Pessimistic', 'Close match', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/15/84336.jpg'),
('Okabe Rintarou', 'You', 'Arcade', 'Raiding a castle', 'Pessimistic', 'Easy win', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/6/122643.jpg'),
('Makise Kurisu', 'You', 'Cafe', 'Sharing an ice-cream cone', 'Optimistic', 'Lose on purpose', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/12/492885.jpg'),
('Shiina Mayuri', 'Them', 'Park', 'Getting headpats', 'Pessimistic', 'Lose on purpose', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/4/131329.jpg'),
('Hashida Itaru', 'Them', 'Cafe', 'Raiding a castle', 'Pessimistic', 'Close match', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/6/113767.jpg'),
('Amane Suzuha', 'Them', 'Park', 'Defends you with their life', 'Pretentious', 'Close win', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/3/148223.jpg'),
('Urushibara Ruka', 'You', 'Cafe', 'Sharing an ice-cream cone', 'Optimistic', 'Tactical', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/7/133805.jpg'),
('Kiryuu Moeka', 'You', 'Cinema', 'Getting headpats', 'Optimistic', 'Tactical', 'Murder', 'https://cdn.myanimelist.net/images/characters/12/275310.jpg'),
('Yeager Eren', 'You', 'Park', 'Getting headpats', 'Pretentious', 'Close win', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/10/216895.jpg'),
('Ackerman Mikasa', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Optimistic', 'Tactical', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/9/215563.jpg'),
('Levi Rivaille', 'You', 'Arcade', 'Raiding a castle', 'Pretentious', 'Close win', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/2/241413.jpg'),
('Arlert Armin', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Possessive', 'Tactical', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/8/220267.jpg'),
('Jaeger Grisha', 'You', 'Park', 'Getting headpats', 'Optimistic', 'Complete loss', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/6/206441.jpg'),
('Smith Erwin', 'Them', 'Cinema', 'Raiding a castle', 'Pessimistic', 'Easy win', 'Murder', 'https://cdn.myanimelist.net/images/characters/14/559023.jpg'),
('Zoë Hange', 'You', 'Park', 'Sharing an ice-cream cone', 'Possessive', 'Close win', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/15/208637.jpg'),
('Blouse Sasha', 'Them', 'Cafe', 'Getting headpats', 'Optimistic', 'Tactical', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/6/251937.jpg'),
('Braun Reiner', 'You', 'Arcade', 'Sharing an ice-cream cone', 'Pessimistic', 'Complete loss', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/16/206489.jpg'),
('Kirstein Jean', 'Them', 'Cinema', 'Raiding a castle', 'Possessive', 'Easy win', 'Murder', 'https://cdn.myanimelist.net/images/characters/14/216893.jpg'),
('Ackerman Kenny', 'You', 'Park', 'Getting headpats', 'Optimistic', 'Tactical', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/8/364347.jpg'),
('Reiss Historia', 'Them', 'Cafe', 'Raiding a castle', 'Pessimistic', 'Complete loss', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/16/216967.jpg'),
('Leonhart Annie', 'You', 'Park', 'Getting headpats', 'Optimistic', 'Tactical', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/9/206357.jpg'),
('Shinomiya Kaguya', 'You', 'I don''t care', 'Getting headpats', 'Optimistic', 'Complete loss', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/2/504723.jpg'),
('Ishigami Yuu', 'You', 'Arcade', 'Raiding a castle', 'Pretentious', 'Close match', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/7/372840.jpg'),
('Fujiwara Chika', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Pessimistic', 'Tactical', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/15/559031.jpg'),
('Shirogane Miyuki', 'You', 'Park', 'Getting headpats', 'Optimistic', 'Tactical', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/16/371541.jpg'),
('Iino Miko', 'You', 'Cafe', 'Sharing an ice-cream cone', 'Optimistic', 'Easy win', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/16/376603.jpg'),
('Hayasaka Ai', 'Them', 'I don''t care', 'Raiding a castle', 'Pretentious', 'Complete loss', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/8/504012.jpg'),
('Okazaki Tomoya', 'You', 'I don''t care', 'Sharing an ice-cream cone', 'Optimistic', 'Tactical', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/6/508343.jpg'),
('Furukawa Nagisa', 'You', 'Park', 'Getting headpats', 'Pessimistic', 'Complete loss', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/3/300961.jpg'),
('Okazaki Ushio', 'Them', 'Park', 'Sharing an ice-cream cone', 'Pessimistic', 'Lose on purpose', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/12/48244.jpg'),
('Sakagami Tomoyo', 'You', 'Park', 'Defends you with their life', 'Possessive', 'Complete loss', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/2/34293.jpg'),
('Fujibayashi Kyou', 'You', 'Arcade', 'Getting headpats', 'Pessimistic', 'Complete loss', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/11/52002.jpg'),
('Fujibayashi Ryou', 'Them', 'Arcade', 'Getting headpats', 'Pretentious', 'Easy win', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/9/256501.jpg'),
('Gojo Satoru', 'Them', 'Arcade', 'Raiding a castle', 'Pessimistic', 'Complete loss', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/15/422168.jpg'),
('Itadori Yuuji', 'Them', 'Arcade', 'Raiding a castle', 'Pretentious', 'Complete loss', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/6/467646.jpg'),
('Fushiguro Megumi', 'You', 'I don''t care', 'Defends you with their life', 'Optimistic', 'Close match', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/2/392689.jpg'),
('Kugisaki Nobara', 'Them', 'Arcade', 'Raiding a castle', 'Pessimistic', 'Complete loss', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/12/422313.jpg'),
('Nanami Kento', 'You', 'Park', 'Defends you with their life', 'Optimistic', 'Complete loss', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/16/581424.jpg'),
('Ryomen Sukuna', 'Them', 'Arcade', 'Raiding a castle', 'Pessimistic', 'Complete loss', 'Murder', 'https://cdn.myanimelist.net/images/characters/6/431152.jpg'),
('Okkotsu Yuuta', 'Them', 'Park', 'Getting headpats', 'Pretentious', 'Tactical', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/10/461503.jpg'),
('Fushiguro Toji', 'Them', 'Arcade', 'Raiding a castle', 'Pessimistic', 'Complete loss', 'Murder', 'https://cdn.myanimelist.net/images/characters/2/517123.jpg'),
('Zenin Maki', 'Them', 'I don''t care', 'Defends you with their life', 'Pretentious', 'Complete loss', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/3/440469.jpg'),
('Inumaki Toge', 'You', 'Cafe', 'Sharing an ice-cream cone', 'Possessive', 'Complete loss', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/4/521636.jpg'),
('Panda', 'You', 'Park', 'Getting headpats', 'Optimistic', 'Close match', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/16/423950.jpg'),
('Senjougahara Hitagi', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Optimistic', 'Tactical', 'Murder', 'https://cdn.myanimelist.net/images/characters/11/287902.jpg'),
('Araragi Koyomi', 'You', 'Park', 'Getting headpats', 'Optimistic', 'Tactical', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/16/559456.jpg'),
('Hanekawa Tsubasa', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Pessimistic', 'Complete loss', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/3/288080.jpg'),
('Oshino Shinobu', 'You', 'Park', 'Sharing an ice-cream cone', 'Pessimistic', 'Close win', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/6/322539.jpg'),
('Oshino Meme', 'Them', 'Arcade', 'Raiding a castle', 'Optimistic', 'Tactical', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/7/532734.jpg'),
('Kanbaru Suruga', 'You', 'Park', 'Sharing an ice-cream cone', 'Pessimistic', 'Close win', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/11/222449.jpg'),
('Hachikuji Mayoi', 'Them', 'Cafe', 'Getting headpats', 'Optimistic', 'Easy win', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/5/222381.jpg'),
('Sengoku Nadeko', 'You', 'Park', 'Sharing an ice-cream cone', 'Possessive', 'Close win', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/2/264877.jpg'),
('Nakano Ichika', 'Them', 'Cinema', 'Sharing an ice-cream cone', 'Possessive', 'Close match', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/12/436646.jpg'),
('Nakano Nino', 'Them', 'Cinema', 'Sharing an ice-cream cone', 'Optimistic', 'Tactical', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/7/437011.jpg'),
('Nakano Miku', 'You', 'Arcade', 'Sharing an ice-cream cone', 'Optimistic', 'Lose on purpose', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/15/507743.jpg'),
('Nakano Yotsuba', 'Them', 'Arcade', 'Raiding a castle', 'Pessimistic', 'Close match', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/8/437009.jpg'),
('Nakano Itsuki', 'You', 'I don''t care', 'Getting headpats', 'Possessive', 'Tactical', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/5/437010.jpg'),
('Makima', 'Them', 'I don''t care', 'Getting headpats', 'Possessive', 'Complete loss', 'Murder', 'https://cdn.myanimelist.net/images/characters/4/489561.jpg'),
('Denji', 'Them', 'Cafe', 'Raiding a castle', 'Pretentious', 'Complete loss', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/3/492407.jpg'),
('Power', 'Them', 'Arcade', 'Raiding a castle', 'Possessive', 'Complete loss', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/7/494969.jpg'),
('Himeno', 'Them', 'Cinema', 'Getting headpats', 'Possessive', 'Complete loss', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/12/386392.jpg'),
('Mizuhara Chizuru', 'You', 'Cinema', 'Getting headpats', 'Pretentious', 'Close match', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/4/484261.jpg'),
('Sakurasawa Sumi', 'You', 'Cafe', 'Sharing an ice-cream cone', 'Possessive', 'Complete loss', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/9/484263.jpg'),  
('Sarashina Ruka', 'Them', 'Arcade', 'Raiding a castle', 'Pessimistic', 'Close match', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/11/409385.jpg'),  
('Nanami Mami', 'Them', 'I don''t care', 'Defends you with their life', 'Optimistic', 'Easy win', 'Murder', 'https://cdn.myanimelist.net/images/characters/4/491833.jpg'),  
('Kinoshita Kazuya', 'Them', 'Cinema', 'Getting headpats', 'Pretentious', 'Lose on purpose', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/9/396701.jpg'),  
('Kamado Tanjiro', 'Them', 'Cafe', 'Defends you with their life', 'Pretentious', 'Complete loss', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/9/396701.jpg'),
('Nezuko Kamado', 'You', 'Cafe', 'Getting headpats', 'Pretentious', 'Complete loss', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/2/378254.jpg'),
('Zenitsu Agatsuma', 'Them', 'I don''t care', 'Raiding a castle', 'Optimistic', 'Close match', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/10/459689.jpg'),
('Inosuke Hashibira', 'Them', 'Arcade', 'Raiding a castle', 'Pessimistic', 'Complete loss', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/3/329560.jpg'),
('Shinobu Kocho', 'Them', 'Park', 'Getting headpats', 'Optimistic', 'Complete loss', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/3/386591.jpg'),
('Giyuu Tomioka', 'You', 'I don''t care', 'Defends you with their life', 'Optimistic', 'Complete loss', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/3/423445.jpg'),
('Kyojuro Rengoku', 'Them', 'Cinema', 'Getting headpats', 'Pessimistic', 'Complete loss', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/10/423443.jpg'),
('Tengen Uzui', 'Them', 'Cinema', 'Raiding a castle', 'Possessive', 'Complete loss', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/16/387706.jpg'),
('Mitsuri Kanroji', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Pessimistic', 'Lose on purpose', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/16/387706.jpg'),
('Muzan Kibutsuji', 'Them', 'Cinema', 'Getting headpats', 'Optimistic', 'Complete loss', 'Murder', 'https://cdn.myanimelist.net/images/characters/4/384669.jpg'),
('Midoriya Izuku', 'You', 'Arcade', 'Defends you with their life', 'Pretentious', 'Tactical', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/7/299404.jpg'),
('Aisaka Taiga', 'You', 'Arcade', 'Raiding a castle', 'Optimistic', 'Complete loss', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/11/514086.jpg'),
('Akame', 'You', 'I don''t care', 'Defends you with their life', 'Pretentious', 'Complete loss', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/8/253095.jpg'),
('Zero Two', 'Them', 'Cafe', 'Getting headpats', 'Pessimistic', 'Complete loss', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/14/559013.jpg'),
('Rudeus Greyrat', 'You', 'Arcade', 'Raiding a castle', 'Possessive', 'Easy win', 'Murder', 'https://cdn.myanimelist.net/images/characters/2/423667.jpg'),
('Roxy Migurdia', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Pretentious', 'Tactical', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/16/552605.jpg'),  
('Eris Boreas Greyrat', 'You', 'Raiding a castle', 'Defends you with their life', 'Pessimistic', 'Close match', 'Murder', 'https://cdn.myanimelist.net/images/characters/14/324594.jpg'),  
('Sylphiette', 'Them', 'Park', 'Getting headpats', 'Possessive', 'Complete loss', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/10/423669.jpg'),  
('Hoshino Aqua', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Pessimistic', 'Complete loss', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/8/512509.jpg'),
('Ruby Hoshino', 'Them', 'Arcade', 'Sharing an ice-cream cone', 'Pessimistic', 'Complete loss', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/5/496454.jpg'),  
('Akane Kurokawa', 'Them', 'Cafe', 'Defends you with their life', 'Possessive', 'Tactical', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/5/512681.jpg'),  
('Kana Arima', 'You', 'Cinema', 'Getting headpats', 'Pretentious', 'Close match', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/6/503733.jpg'),  
('Mem-Cho', 'You', 'Park', 'Sharing an ice-cream cone', 'Optimistic', 'Lose on purpose', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/8/507015.jpg'),  
('Miyako Saitou', 'Them', 'I don’t care', 'Raiding a castle', 'Pretentious', 'Easy win', 'Murder', 'https://cdn.myanimelist.net/images/characters/11/511321.jpg'),  
('Kousei Arima', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Possessive', 'Complete loss', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/4/273755.jpg'),  
('Tsubaki Sawabe', 'You', 'Park', 'Getting headpats', 'Pretentious', 'Close match', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/11/252841.jpg'),  
('Ryota Watari', 'You', 'Cinema', 'Sharing an ice-cream cone', 'Pessimistic', 'Easy win', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/11/252841.jpg'),  
('Emi Igawa', 'Them', 'Arcade', 'Defends you with their life', 'Optimistic', 'Tactical', 'Murder', 'https://cdn.myanimelist.net/images/characters/10/290707.jpg'),  
('Takeshi Aiza', 'You', 'Raiding a castle', 'Raiding a castle', 'Possessive', 'Easy win', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/7/277320.jpg'),  
('Miyazono Kaori', 'Them', 'Cinema', 'Raiding a castle', 'Pessimistic', 'Easy win', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/14/269375.jpg'),
('David Martinez', 'Them', 'Arcade', 'Raiding a castle', 'Pretentious', 'Close win', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/11/483437.jpg'),
('Lucy', 'Them', 'Park', 'Defends you with their life', 'Possessive', 'Tactical', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/11/486620.jpg'),  
('Rebecca', 'You', 'Arcade', 'Raiding a castle', 'Pessimistic', 'Close match', 'Murder', 'https://cdn.myanimelist.net/images/characters/16/547499.jpg'),  
('Maine', 'You', 'I don’t care', 'Defends you with their life', 'Pretentious', 'Easy win', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/12/489196.jpg'),  
('Adam Smasher', 'You', 'Raiding a castle', 'Raiding a castle', 'Optimistic', 'Easy win', 'Murder', 'https://cdn.myanimelist.net/images/characters/8/488106.jpg'),  
('Kiwi', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Possessive', 'Tactical', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/8/488106.jpg'),  
('Sakuta Azusagawa', 'Them', 'I don''t care', 'Defends you with their life', 'Pretentious', 'Tactical', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/11/398261.jpg'),
('Mai Sakurajima', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Pretentious', 'Tactical', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/2/366639.jpg'),  
('Rio Futaba', 'Them', 'I don’t care', 'Getting headpats', 'Optimistic', 'Close match', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/2/366639.jpg'),  
('Tomoe Koga', 'You', 'Arcade', 'Sharing an ice-cream cone', 'Possessive', 'Complete loss', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/4/366709.jpg'),  
('Kaede Azusagawa', 'Them', 'Park', 'Getting headpats', 'Pessimistic', 'Lose on purpose', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/7/366710.jpg'),  
('Shouko Makinohara', 'Them', 'Cinema', 'Defends you with their life', 'Possessive', 'Tactical', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/3/572435.jpg'),  
('Nodoka Toyohama', 'You', 'Raiding a castle', 'Raiding a castle', 'Pretentious', 'Easy win', 'Murder', 'https://cdn.myanimelist.net/images/characters/3/572435.jpg'),  
('Hikigaya Hachiman', 'Them', 'I don''t care', 'Raiding a castle', 'Optimistic', 'Tactical', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/3/572435.jpg'),
('Yukino Yukinoshita', 'Them', 'Cafe', 'Defends you with their life', 'Pretentious', 'Tactical', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/11/319053.jpg'),  
('Yui Yuigahama', 'You', 'Park', 'Getting headpats', 'Pessimistic', 'Complete loss', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/11/319053.jpg'),  
('Iroha Isshiki', 'Them', 'Cinema', 'Sharing an ice-cream cone', 'Optimistic', 'Lose on purpose', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/8/320273.jpg'),  
('Saki Kawasaki', 'You', 'I don’t care', 'Defends you with their life', 'Possessive', 'Close match', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/11/309088.jpg'),  
('Shizuka Hiratsuka', 'You', 'Raiding a castle', 'Raiding a castle', 'Pretentious', 'Easy win', 'Murder', 'https://cdn.myanimelist.net/images/characters/6/523242.jpg'),  
('Ciel Phantomhive', 'You', 'I don''t care', 'Raiding a castle', 'Optimistic', 'Easy win', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/9/253757.jpg'),
('Sebastian Michaelis', 'Them', 'Cafe', 'Defends you with their life', 'Pessimistic', 'Easy win', 'Murder', 'https://cdn.myanimelist.net/images/characters/6/44160.jpg'),  
('Miyamura Izumi', 'Them', 'I don''t care', 'Raiding a castle', 'Pretentious', 'Complete loss', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/12/507110.jpg'),
('Kyoko Hori', 'You', 'Arcade', 'Defends you with their life', 'Possessive', 'Close match', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/12/507110.jpg'),  
('Yuki Yoshikawa', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Pessimistic', 'Lose on purpose', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/9/424143.jpg'),  
('Remi Ayasaki', 'You', 'Park', 'Getting headpats', 'Pretentious', 'Complete loss', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/8/422261.jpg'),  
('Shuu Iura', 'You', 'Cinema', 'Sharing an ice-cream cone', 'Optimistic', 'Easy win', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/8/422261.jpg'),  
('Kakeru Sengoku (Shindo)', 'Them', 'I don’t care', 'Raiding a castle', 'Possessive', 'Tactical', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/14/318218.jpg'),  
('Kyousuke Hori', 'You', 'Raiding a castle', 'Defends you with their life', 'Pretentious', 'Easy win', 'Murder', 'https://cdn.myanimelist.net/images/characters/7/318212.jpg'),  
('Tooru Ishikawa', 'Them', 'Arcade', 'Getting headpats', 'Pessimistic', 'Close match', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/6/424144.jpg'),  
('Tohru Honda', 'Them', 'Park', 'Getting headpats', 'Pretentious', 'Lose on purpose', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/2/384113.jpg'),
('Kasumigaoka Utaha', 'Them', 'Cafe', 'Getting headpats', 'Optimistic', 'Close match', 'Murder', 'https://cdn.myanimelist.net/images/characters/8/325309.jpg'),
('Megumi Kato', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Pretentious', 'Tactical', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/6/291382.jpg'),  
('Eriri Spencer Sawamura', 'You', 'Arcade', 'Getting headpats', 'Possessive', 'Close match', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/4/325308.jpg'),  
('Michiru Hyodo', 'You', 'Park', 'Raiding a castle', 'Optimistic', 'Easy win', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/11/325311.jpg'),  
('Tomoya Aki', 'Them', 'Cinema', 'Defends you with their life', 'Pessimistic', 'Complete loss', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/8/278182.jpg'),  
('Narumi Momose', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Pessimistic', 'Lose on purpose', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/12/348855.jpg'),
('Hirotaka Nifuji', 'Them', 'Arcade', 'Sharing an ice-cream cone', 'Pretentious', 'Tactical', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/3/348857.jpg'),  
('Hanako Koyanagi', 'You', 'Cafe', 'Defends you with their life', 'Possessive', 'Close match', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/7/348851.jpg'),  
('Tarou Kabakura', 'You', 'I don’t care', 'Raiding a castle', 'Pessimistic', 'Easy win', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/5/348854.jpg'),  
('Kitagawa Marin', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Pretentious', 'Easy win', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/10/459773.jpg'),
('Wakana Gojou', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Pretentious', 'Complete loss', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/5/472608.jpg'),  
('Ayuzawa Misaki', 'You', 'I don''t care', 'Getting headpats', 'Pessimistic', 'Complete loss', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/9/35808.jpg'),
('Takumi Usui', 'You', 'Cafe', 'Defends you with their life', 'Pretentious', 'Easy win', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/9/282968.jpg'),  
('Onodera Kosaki', 'You', 'Cafe', 'Sharing an ice-cream cone', 'Pretentious', 'Lose on purpose', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/9/241653.jpg'),
('Chitoge Kirisaki', 'You', 'Arcade', 'Defends you with their life', 'Possessive', 'Close match', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/9/223517.jpg'),  
('Raku Ichijou', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Pessimistic', 'Tactical', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/12/242215.jpg'),  
('Seishiro Tsugumi', 'Them', 'Raiding a castle', 'Raiding a castle', 'Pretentious', 'Easy win', 'Arrested for a good cause', 'https://cdn.myanimelist.net/images/characters/8/241659.jpg'),  
('Marika Tachibana', 'You', 'Park', 'Getting headpats', 'Optimistic', 'Lose on purpose', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/13/241915.jpg'),  
('Ruri Miyamoto', 'Them', 'Cafe', 'Sharing an ice-cream cone', 'Pretentious', 'Tactical', 'Falsely accused', 'https://cdn.myanimelist.net/images/characters/9/235033.jpg'),  
('Shuu Maiko', 'You', 'Arcade', 'Raiding a castle', 'Optimistic', 'Close match', 'Something stupid', 'https://cdn.myanimelist.net/images/characters/7/235031.jpg');

